apiVersion: v1
kind: Service
metadata:
  name: tuvarna-service
  namespace: tuvarna
  labels:
    degree: phd
    version: v1

spec:
  type: NodePort
  sessionAffinity: None
  selector:
    degree: phd
    version: v1
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432

