http:
  middlewares:
    SslHeader:
      headers:
        FrameDeny: true
        AccessControlAllowMethods: 'GET,OPTIONS,PUT'
        AccessControlAllowOriginList:
          - origin-list-or-null
        AccessControlMaxAge: 100
        AddVaryHeader: true
        BrowserXssFilter: true
        ContentTypeNosniff: true
        ForceSTSHeader: true
        STSIncludeSubdomains: true
        STSPreload: true
        #ContentSecurityPolicy: default-src 'self' 'unsafe-inline'
        ContentSecurityPolicy: >
          default-src 'self';
          script-src 'self' https://cdnjs.cloudflare.com https://unpkg.com;
          font-src 'self' https://fonts.gstatic.com;
          style-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com;
        CustomFrameOptionsValue: SAMEORIGIN
        ReferrerPolicy: same-origin
        PermissionsPolicy: vibrate 'self'
        STSSeconds: 315360000
